name: mapesa
description: A test project for the UI/UX developer interview.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Package for stylish transition between pages
  page_transition: ^2.0.9

  #Package for creating launcher icons
  flutter_launcher_icons: ^0.10.0

  #Package for creating a splash screen
  flutter_native_splash: ^2.2.9

  #Package that enables widget and text animation
  widget_and_text_animator: ^1.0.9

  #Package to display data in a pie chart
  pie_chart: ^5.3.2

  #Package to enable responsive scaling on various devices
  relative_scale: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mapesa.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/mapesa.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/mapesa.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:


  uses-material-design: true

  assets:
    - assets/wp-1.jpg
    - assets/transaction_data.json
    - assets/expense_data.json
    - assets/income_data.json
    - assets/loans_data.json
    - assets/savings_data.json
    - assets/mapesa_user_icon.png
    - assets/images/

  